PILOT-1968: delete local common module
PilotDataPlatform/dataset pull request #100
Opened 2022-11-24 14:47 UTC by hugoantunes

## Summary

- remove MinioClient
- add s3_client.boto_client.stat_object to version preview stream
- user s3_client in PublishVersion
- add S3Client.upload_file to upload file without read file body
- remove mock_minio fixture
- fix tests

## JIRA Issues

https://indocconsortium.atlassian.net/browse/PILOT-1968

## Type of Change

Please delete options that are not relevant.

- [x] Refactor or reformatting

## Testing

Are there any new or updated tests to validate the changes?

- [x] Yes
- [ ] No

## Test Directions

- Dataset version should continue work.
- Dataset preview should continue work.

2022-11-24 17:43 UTC, vmoshynskyi requested changes
Please check my suggestions.

2022-11-24 17:43 UTC, vmoshynskyi commented on dataset/routers/v1/api_version/publish_version.py
> +                    location_data['bucket'], location_data['path'], self.tmp_folder + '/' + location_data['path']
I would suggest to introduce e.g. a `download_file` method into `S3Client` and use it instead of accessing the internal `boto_client`.
```suggestion
                await self.s3_client.download_file(
                    location_data['bucket'], location_data['path'], self.tmp_folder + '/' + location_data['path']
```

2022-11-24 17:43 UTC, vmoshynskyi commented on tests/api_versions/test_versions.py
> +    await s3_client.boto_client.upload_object(dataset.code, 'obj/path', '')
```suggestion
    await s3_client.upload_file(dataset.code, 'obj/path', '')
```

2022-11-24 17:46 UTC, hugoantunes commented on dataset/components/object_storage/s3.py
> +            await s3.upload_file(file_path, bucket, file_key)
it's not the same method, the one in the boto client requires the file body. this one doesn't. I added that because its a zip file that contains other files as I thought would make more sense let the boto3 lib deal with that. 

I already talked to @colorzzr and first, we will validate this method in dev. Working we will add this to the boto_client in the common package as well.

2022-11-24 17:49 UTC, hugoantunes commented on dataset/components/object_storage/s3.py
> +            await s3.upload_file(file_path, bucket, file_key)
the common lib is using [put_file](https://github.com/PilotDataPlatform/common/blob/f95ef4918af9d7be5ca37f1a712ca51d465c293c/common/object_storage_adaptor/boto3_client.py#L209)

2022-11-25 10:00 UTC, hugoantunes commented on tests/api_versions/test_versions.py
> +    await s3_client.boto_client.upload_object(dataset.code, 'obj/path', '')
@vmoshynskyi I think it's better like this because otherwise, I would need to create a file. 
`upload_object ` creates a file with the given body in the given path. 
`upload_file ` creates a file given the local path and the bucket.

2022-11-25 10:24 UTC, vmoshynskyi approved these changes
👍

2022-11-25 10:24 UTC, vmoshynskyi commented on dataset/components/object_storage/s3.py
> +            await s3.upload_file(file_path, bucket, file_key)
Ah, I see. Okay.

2022-11-25 10:24 UTC, vmoshynskyi commented on tests/api_versions/test_versions.py
> +    await s3_client.boto_client.upload_object(dataset.code, 'obj/path', '')
Okay, agreed!

2022-11-25 10:27 UTC, merged