PILOT-1820: fix alembic docker image
PilotDataPlatform/dataset pull request #78
Opened 2022-10-19 10:58 UTC by hugoantunes

## Summary

- fix alembic docker image
- replace ${{env.app_version}} with ${{steps.get_version.outputs.app_version}} in create release step

## JIRA Issues

https://indocconsortium.atlassian.net/browse/PILOT-1820

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Refactor or reformatting

## Testing

Are there any new or updated tests to validate the changes?

- [ ] Yes
- [x] No

## Test Directions

N/A

2022-10-19 14:32 UTC, andricDu requested changes

2022-10-19 14:32 UTC, andricDu commented on .github/workflows/build-and-publish.yml
> +      app_version: ${{steps.get_version.outputs.app_version}}
needs to be pulled out into its own job so it can be referenced through a `needs`

2022-10-19 18:09 UTC, andricDu approved these changes

2022-10-20 14:27 UTC, vmoshynskyi approved these changes

2022-10-20 17:16 UTC, merged