Pilot 1802
PilotDataPlatform/dataset pull request #84
Opened 2022-10-25 20:06 UTC by hugoantunes

## Summary

(Summarize the changes)

## JIRA Issues

(What JIRA issues this merge request is related to)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Refactor or reformatting

## Testing

Are there any new or updated tests to validate the changes?

- [ ] Yes
- [ ] No

## Test Directions

(Additional instructions for how to run tests or validate functionality if not covered by unit tests)

2022-10-26 15:21 UTC, vmoshynskyi requested changes
Please check my comments.

2022-10-26 15:21 UTC, vmoshynskyi commented on app/components/object_storage/policy.py
> +class PolicyManager:
I think we have this already in common package. Can we use that?
https://github.com/PilotDataPlatform/common/blob/8532b95754a11001f236466b909a4182c21b123d/common/object_storage_adaptor/minio_policy_client.py#L37

2022-10-26 15:21 UTC, vmoshynskyi commented on app/components/object_storage/policy_templates.py
> +TEMPLATES_LIBRARY = get_policy_template
I suggest to use a dictionary here since library assumes more than one template. Or just use single `get_policy_template` function instead of `TEMPLATES_LIBRARY` var.
```suggestion
TEMPLATES_LIBRARY = {
  'some-name': get_policy_template,
}
```

2022-10-26 15:21 UTC, vmoshynskyi commented on app/components/object_storage/s3.py
> +    TODO: move this class to the common package (https://indocconsortium.atlassian.net/browse/PILOT-1500)
I think this TODO is not relevant here.
```suggestion
```

2022-10-26 15:21 UTC, vmoshynskyi commented on app/components/object_storage/s3.py
> +    async def remove_bucket(self, bucket: str) -> dict[str, Any]:
We have this already in common package I think it's better to reuse that logic.
https://github.com/PilotDataPlatform/common/blob/8532b95754a11001f236466b909a4182c21b123d/common/object_storage_adaptor/boto3_admin_client.py#L86

2022-10-26 15:21 UTC, vmoshynskyi commented on app/services/dataset.py
> +    async def create_essentials(self, db, dataset):
Typings are missed.

2022-10-27 10:28 UTC, vmoshynskyi approved these changes
LGTM!

2022-10-28 08:31 UTC, hugoantunes commented
This PR also required changes in BFF:
https://github.com/PilotDataPlatform/bff-web/pull/146

2022-10-31 14:04 UTC, merged